services:
  crud:
    container_name: crud
    image: benevanio/crud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
    - DB_TYPE=postgres
    - DB_HOST=db
    - DB_PORT=5432  
    - DB_USERNAME=postgres 
    - DB_PASSWORD=postgres  
    - DB_NAME=crud  
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
